### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#157]
what does being a contributor actually do???
LOL

I am GitDumb and need an edumication (not a type. done intentionally)

**Comment by per1234** [comment]
Contributor means you've had at least one of your Pull Requests merged. You're actually one step up from Contributor now, Collaborator!

**Comment by kdschlosser** [comment]
Oh ok. well explain that then..

**Comment by per1234** [comment]
Collaborators have some level of permissions in the repository: Read, write, and/or admin. The level of your permissions are set by a repository admin or owner. I don't know what permission level you're at so I can't say exactly which actions you're permitted. I'd guess examples of things you can do are review other people's pull requests so that they can be merged and close other people's issues.

**Comment by topic2k** [comment]
Sorry @kdschlosser if i made you wonder.  :)  I totaly forgot to inform you, that i invited you and others to be (outside) collaborators. The reason is, that you can now [approve](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/) pull request. It's just for qualitiy control :D I still can merge PRs that are not approved, but it looks nicer if there is more green:  :wink:

![approved](https://cloud.githubusercontent.com/assets/6463113/21614366/7acaea00-d1d9-11e6-8d67-5b16d11c8dc5.png)

**Comment by kdschlosser** [comment]
ok so i can review now. Cool beans. Thanks. Its amazing because I think back and 2 years ago i never programmed a thing. and I remember @per1234 saying to me. "You will be editing the EventGhost core code in no time". and I remember looking at it thinking. it's a bloody mystery LOL
