### ISSUE TITLE
Bug Report Format

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#158]
I have noticed. In the forum under the Beta Bug Reports. because i have that template that shows POW right in your face. (and I do know it's annoying but that's the point) It works. people are formatting the bug reports in a consistent manner. and there is no need to ask for this information. It has really simplified the process for us as well as the user.

Is there a way to do this same king of thing here as well??

**Comment by per1234** [comment]
When you create an issue GitHub shows the text
>Please review the guidelines for contributing to this repository.

Which links to [CONTRIBUTING.md](https://github.com/EventGhost/EventGhost/blob/master/CONTRIBUTING.md). So I think if any information is missing from the ["Things to include in your bug report"](https://github.com/EventGhost/EventGhost/blob/master/CONTRIBUTING.md#things-to-include-in-your-bug-report) section of that file they should just be added there.

I think having issue report guidelines in CONTRIBUTING.md should be sufficient to get good bug reports. If not there is a way to automatically add text directly to issue reports(and pull requests):
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by kdschlosser** [comment]
the template thing is a great way to go about it. and its pretty easy to implement as well.

but what i do not care for is the issues button being for everything

issues, questions, feature requests. this i do not like. but it is hot github functions

**Comment by per1234** [comment]
>issues, questions, feature requests.

Yes, that's why I'm not crazy about the template idea. It's impossible to make it work for all possible uses of issues. That may end up causing confusion, as I could see happening with the checkboxes example in the blog post.

**Comment by topic2k** [comment]
+1 👍  We will keep it the current way, the github default link to CONTRIBUTING.md.

**Comment by kdschlosser** [comment]
i do agree on this.. some things github just needs to change it would make things easier.

**Comment by per1234** [comment]
I'm not necessarily advocating for this unless we start seeing problems with people not reading CONTRIBUTING.md but just to document the idea here: I added the following Issue and Pull Request templates to my repositories:

PULL_REQUEST_TEMPLATE.md:
>Read the Pull Requests section of the Contribution Rules at the "guidelines for contributing" link above before submitting a pull request.

ISSUE_TEMPLATE.md:
>Read the Issues section of the Contribution Rules at the "guidelines for contributing" link above before submitting an issue report.

I think this will give an extra nudge to people who might otherwise ignore the less direct "Please review the [guidelines for contributing](https://github.com/EventGhost/EventGhost/blob/master/CONTRIBUTING.md) to this repository.", yet will not cause any confusion. I don't get any contributors to my repositories but just today it did successfully redirect a support request to be made on a forum instead.
