### ISSUE TITLE
Turn On/Off Monitor action freezes EventGhost

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#181]
EventGhost version: [WIP-2017.01.16-20.30.34 Appveyor build](https://ci.appveyor.com/project/topic2k/eventghost/build/362-master/artifacts)
Operating System: Windows 7 64 bit

After some time of working correctly, executing the System plugin's **Turn On Monitor**, **Turn Off Monitor**, or **Turn Off Monitor (Standby)** actions causes EventGhost to no longer receive events, execute events, or add tree items. The application is not fully frozen, I can still open the menus and the context menu but it does freeze after trying to add a new tree item once the issue has occurred. This occurs even with an otherwise empty tree file. The action that causes the issue to start does execute(e.g. monitor turns off when Turn Off Monitor action is executed). There is no error shown in the log. After restarting EventGhost it can execute actions, receive events, etc. but the first time I execute one of the monitor power actions the issue occurs again. If I restart my computer the problem goes away but then comes back after some time (hours). I have been unable to determine what specific conditions cause EventGhost to go from the working to the non-working state. I have tried repeated cycles of Turn Off Monitor/Turn On Monitor dozens of times and this does not cause EventGhost to go from the working to non-working state.

If I revert https://github.com/EventGhost/EventGhost/commit/f62356cf1838cc1c6ab0890e04648416a0d94d47 the actions start working again correctly.

The issue occurs when using [Appveyor build 330](https://ci.appveyor.com/project/topic2k/eventghost/build/330)(the build for https://github.com/EventGhost/EventGhost/commit/f62356cf1838cc1c6ab0890e04648416a0d94d47.

The issue does not occur when using [Appveyor build 329](https://ci.appveyor.com/project/topic2k/eventghost/build/329/artifacts).

 I will continue to investigate what conditions trigger the issue and update this issue if I find any new information. Please let me know if I can provide any additional information

cc: @kdschlosser

**Comment by kdschlosser** [comment]
I am wondering if it is possibly caused by the action turning the monitor off if the computer already has it powered off...

but when you say it comes back again after hours??. explain that statement.. 

has the computer been in use during that whole time?
have the actions been run at all during that time?
was the computer sleeping?

has the action to turn off the monitor run and then the computer went to sleep then you woke it up and the problem occurred?

did the monitor possibly power off first then the action ran to tun it off when the monitor may have already been off?

gotta narrow down the exact cause. but the fact that that your system requires a reboot even tho you killed EG leads me to think it may be a video driver thing. because the system should go back to normal if it was an EG screw up. but... it could be making a call and the video driver doesn't like it.. and gets stuck... that kind of a problem would linger even after killing EG

try upgrading your video card drivers..

if the problem persists I will add some version checking for windows.. it was the monitor turning on that was an issue with windows 8+ but I adapted the code to use the same mechanism. but we can try to narrow down the issue as far as what action is causing it...

so in order to turn you monitor back on do not use an action.. do it with the mouse.. and if the problem shows up then we know it's the Off action causing it.

and if not then we will try it with the power on. and disable the power off action... I am thinking it will be an issue with the power on.. I can make some code changes and put it up on a branch. all you would have to do is to replace the __init__ file in the system plugin.. but I would like to know which action so i am not just poking at it not knowing where..

**Comment by per1234** [comment]
>I am wondering if it is possibly caused by the action turning the monitor off if the computer already has it powered off...

No, definitely not. My computer never powers off my monitor, only EventGhost
>but when you say it comes back again after hours??. explain that statement..

I mean that after restarting my computer Turn Off/On Monitor works correctly and no matter what I do I can't seem to trigger the issue. At some point after that hours later the system becomes "susceptible" to the issue. By "susceptible" I mean that anytime the Turn Off/On Monitor actions are executed the issue occurs, even after restarting EventGhost. I need to restart my computer to make it no longer "susceptible" to the issue, then hours after that it becomes "susceptible" again. I'm not sure if its just a matter of time or something I've done, either in EventGhost or the computer in general during that time.
>has the computer been in use during that whole time?

There are events constantly being triggered in EventGhost but I'm not necessarily actively using the computer the whole time.
>have the actions been run at all during that time?

Yes, the Turn Monitor On/Off actions are executed from time to time (normally every couple hours).
>was the computer sleeping?

No, never sleeping
>has the action to turn off the monitor run and then the computer went to sleep then you woke it up and the problem occurred?

No, the computer is never put to sleep.
>did the monitor possibly power off first then the action ran to tun it off when the monitor may have already been off?

No, the monitor is only ever powered on and off by the EventGhost actions.
>try upgrading your video card drivers..

I just ran the update check via Device Manager and it says they are already up to date and also checked on the Intel website and verified this.
>so in order to turn you monitor back on do not use an action.. do it with the mouse.. and if the problem shows up then we know it's the Off action causing it.

I've already done that and Off or On can cause it. Even if the monitor is already on, running the On action will cause the issue when the computer is in its "susceptible" state.

Happy to test a modified version of the plugin. Thanks for looking into this! I know it's not very clear what's going on since I'm not even able to reproduce it until it gets in the "susceptible" state and I don't know how to trigger that state.. I've been trying to narrow it down for a couple days now with no luck so I decided I should just submit an issue report now to see if it was something obvious.

**Comment by kdschlosser** [comment]
I just don't know if it's the off or on that is causing it...


so what I am going to do is alter the plugin so the off and on are back to the way they were. i don't have a windows 8 or 10 computer so i do not have a means to test this, but i will do a version check for windows 8+ and if it is i will use a modified version of the On. since that is where the problem. was.

I would really like to know if this issues is isolated to you or if it is an issue that is across all computers... so give me a day or 2. I am going to give the altered file to someone with a window 8 or 10 and have them run it and see if i can replicate the issues.

**Comment by kdschlosser** [comment]
I am running a couple of tests.. only because we seem to be having a lot of issues with pywin32... and I have read somewhere that pywin32 doesn't work properly when you use pip to install it.

and that is exactly what appveyor is using to do it.. 
So i am messing around with appveyor on my github fork. i have set up appveyor and I am testing right now a variation of the appveyor.yml. there are a couple of ways i can go about installing it. but the hardest thing is the fact that it does not have a /quiet switch to install it... so I have to tinker. I will let you know when i have a successful build and you can test out the artifact and see if maybe that is the cause of the issue.

**Comment by kdschlosser** [comment]
OK I have some kind of a result. but no working fix. But i do want you to test one thing for me

pywin32 installs completely different if you use their installer, pip, or easy_install... all 3 install differently.

so what i want you to try is to download pywin32 from here.. this is an executable.. 
https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/pywin32-220.win32-py2.7.exe/download

You do have to have python 32 bit 2.7.9 installed for this to work

what will happen is EG when it loads will use the pywin32 from the python and not what it has included with it.. 

if the problem goes away we know it's due to how it's being installed with appveyor. and I will have to find some kind of a workaround... because the installer does not allow for a no prompt install.. this can be rectified by converting the thing to an MSI file.. but before i go through that effort i want to know if this is the case and is what is causing the problem.

**Comment by per1234** [comment]
>You do have to have python 32 bit 2.7.9 installed for this to work

Does it matter if regular Python or stackless?

**Comment by kdschlosser** [comment]
nah doesn't matter.

**Comment by kdschlosser** [comment]
any results on this??? I have a really sneaky suspicion on this.. only because of how pywin32 gets installed.. and EG does not account for files changed in the windows system32 folder. and does not add those files when it installs.

i am reaching here for a possible cause..

**Comment by per1234** [comment]
No problems since installing pywin32 but that could be coincidental. It's really hard to say because I don't know what the exact conditions are necessary to reliably reproduce the issue. I think to be sure there's a connection I need to run with this configuration for a couple days and then if there are still no problems go back to the previous configuration to see if it starts happening again.

**Comment by kdschlosser** [comment]
ok no worries.. again i am very suspect because of the modifications pywin32 makes when using the installer.. 

and i also was skimming some information about pywin32 and came across a statement that pywin32 does not work 100% properly if you install it via pip..

as far as getting an appveyor build to install it the right way is not so much an issue. but getting it to install properly when running setup.exe is a whole nothing story. we may have to change out to using an msi installer instead of an executable. the good thing tho is that pywin32 does not make any reg changes. that would be needed just a bunch of uninstall BS. 
i have already begun messing around with making an msi installer for it so it can be installed unattended. and pywin32 can be added to the site_packages folder for EG that way we can make sure that everything is there. and maybe do a file check and move the files if necessary. tho i do not know how windows 8/10 is going to like an application messing around in the system32 folder

not sure how to go about changing out the files in the windows system 32 folder on install of eg... because i am almost 100% it has to deal with the 3 files that get changed/added to the system 32 folder. because those are the only ones that would not get included into the package.. but it may go deeper then that. don't really know.

**Comment by topic2k** [comment]
@kdschlosser : Do you know [chocolatey](https://chocolatey.org)? It's a package manager for windows. Maybe this is the way to install pywin32. It's also usable from appveyor (but i haven't tried it yet). In the appveyor config add a line `- cinst <package>` to the install section (see the line for html workshop). <package> is the name for the wanted app from the [chocolatey package feed](https://chocolatey.org/packages). There already exists a package for [pywin32 version 219](https://chocolatey.org/packages/PyWin32). Maybe you could adapt the script to install version 220.

PS: Before i release a new beta version i will wait for a solution of this issue.

**Comment by kdschlosser** [comment]
the issue does not lie in appveyor.. because py2exe is what builds the installer. html workshop is not included in the setup.exe for EG

what we need to do is figure out a way to get pywin220 to install onto the users computer. or mimic the installation... 

I have a solution rolling around in my head. but i need to know if this is indeed is the problem.

**Comment by kdschlosser** [comment]
@per1234 has everything been good so far??

**Comment by per1234** [comment]
Yes, not a single occurrence. I just uninstalled pywin32 to see if the issue will come back now.

**Comment by kdschlosser** [comment]
ok cool. let me know.. as i told you i am very suspect of this.

**Comment by kdschlosser** [comment]
I would also have to check to see if the files actually get removed from the windows/system32 folder when pywin32 gets uninstalled..

I do not believe it in fact gets fully removed as i have seen bits of it after uninstall in my python/lib/site-packages folder

I will check on this tonight and see if everything does in fact get deleted that it installs.

@topic2k do you know if there is a way to embed into an exe a way to put files into the windows system32 folder and make backups of the originals? if there are originals. I do know about the whole windows file validation crap. but I also do know if you simply move the files and then put the replacements in windows will not have a fit about it

**Comment by topic2k** [comment]
Don't know if embedding is possible, but wouldn't it be enough if we copy them with the installer/setup of EG? Or maybe the dll's could reside somewhere in the EG program path (lib27, \site-packages).

**Comment by per1234** [comment]
>I would also have to check to see if the files actually get removed from the windows/system32 folder when pywin32 gets uninstalled..

I was worried about that. The issue did reoccur last night. So this is evidence that your suspicions regarding the cause of this issue are correct but it's also possible that the issue not happening the whole time after I installed pywin32 was purely coincidental. I wish we had more beta testers using the latest EG build to see if anyone else would have the same problem.

**Comment by kdschlosser** [comment]
I am 99.9% sure this is the problem. because those 3 files have to deal with windows COM objects. which is exactly how messages are sent back and forth to tell windows what to do..

But need not worry... 

Because K is on the task... and he can deliver the goods...
I have a running installer... and it's all done via code.

w00t w00t

so who's good?   come one now.. tell me...

**Comment by kdschlosser** [comment]
I am going to do some more testing with it.. but everything reports as it installed properly... 

But this has also led me to find a whole slew of other things wrong...

like the sys.prefix is pointed to the wrong place
distutils reports the wrong lib folder
and win32com server register points to pythonw.exe and not py27w.exe

which are all now fixed as well except the sys.prefix i only change that for the installation then i change it back. from what i have read it's pointed to the right place initially. but this causes an error in the install. so i point it to where it needs to be for the install. and then return it to it's original value when the install is finished

**Comment by per1234** [comment]
>so who's good? come one now.. tell me...

⬇️  :small_red_triangle_down: :arrow_double_down: :point_down:
 kdschlosser
⬆️ :point_up_2: :arrow_double_up: :point_up:
Thanks!
>if by doing this it resolves the speech plugin issue without the need for a patch

That would be great! I should mention I am using the Speech plugin in my tree. It's possible the Turn On/Off Monitor action issue is only a symptom of an issue somewhere else. The only 3rd party plugins I have installed are a very minor modification to foobar2000 (fix the code to automatically find the installation folder), and [my fork of TCPEvents](https://github.com/per1234/TCPEvents). Both of these have been running in my tree for years without any problems like what's described here.

**Comment by kdschlosser** [comment]
we can cross out fingers and hope this will do the trick... and we really won't know if it does until we release the next beta. and the problems start rolling in...

**Comment by kdschlosser** [comment]
I don't know to much about pywin32... but maybe @topic2k does. I have made this thing up to leek for the 3 files that are needed in the system32 folder... but if those files are there from a previous version it won't go through the install. a much better process would be to just do the install of pywin32 when EG installs. no matter what. because this thing is all set up to delete the old files as well as remove any old reg keys that may be in there. and set everything up all new. but also uninstall... i have no way of accomplishing this... I i want to do a clean uninstall.. pywin32 currently when you uninstall it does not remove the registry entries.. but it does remove the files..

tho they are only used by pywin32 and would cause no issue if they just lay there dormant. but by rights they should be removed with the uninstall of EG

**Comment by kdschlosser** [comment]
I am going through the appveyor build process now. there are some issues which i need to attend to. but nothing huge. but it has also pointed me in a better direction for packaging the needed files.

so i am going to make some changes to the install process. The thing is tho I am going to have to come up with some way of having setup tools.easy_install included with EG but then block if the installer doesn't need to run or has run... but that would also be the way I would know it needs to run on first startup.. i could open the py27.zip file and remove easy_install after the installer has run. this way when i go to do an import of it.. it will fail because it's not there and I know the installer for pywin32 has run...

I think that's a good way of going about it. So i am going to make that change.. so this evening I will get it done..

time to go work on the house.

**Comment by kdschlosser** [comment]
man this is killing me.. I am so close to getting this thing to work right.

But in the process i figured out how to remove all dependency downloads from EG servers in appveyor so all of the downloads come from the developers sites or pipy. which is pretty cool

**Comment by kdschlosser** [comment]
I wanted to give you an update.... I am really close to being done.. maybe tomorrow morning on this... I hope.. it's soo close.

**Comment by kdschlosser** [comment]
https://ci.appveyor.com/api/buildjobs/fl8oqnhj8y0d1xvr/artifacts/_build%2Foutput%2FEventGhost_WIP-2017.01.30-09.27.30_Setup.exe

here is a link to my branch appveyor build. see if this thing works for ya. It installs and seems to run properly on my end.. don't know if you you might find an issue

**Comment by kdschlosser** [comment]
that last build is not working... and there seems to be an API issue that is not allowing me to build anymore.... @topic2k is working on it... but I feel prerry good about this next build..LOL

**Comment by kdschlosser** [comment]
ok the appveyor thing has been fixed.. but now I hit yet another roadblock.... I have to screw around with it some more. I have to build it one more time and run the install again.... I managed to get everything running but only when i run EG as admin.. I am wondering if the installer actually launches EG for the first time as an admin since you have to give those permissions when you launch the installer.. if that is the case then i have this bugger on the fence. if not I have to start from scratch and add pywin32 to the installer it's self. because those files have to be in the syswow64 or system32 folder. and the only way to do that is administrative privileges. or to have the COM objects created as an admin.. either way it's the same crap.. the only hangup to this is going to be if someone wants to use it in a portable manner. they will have to drop it on the new computer and the first time they launch it they will have to do it as admin. I may just have it do a check and if they aren't admin then pitch a fit about it.

**Comment by per1234** [comment]
Thanks for the update. I hope I'm not sending you on a wild goose chase with the pywin32 installation fix. I went for close to a week without a single problem, then it happened again last night. So it is possible I didn't run long enough with the manual installation of pywin32 to be sure it wouldn't happen with that configuration. It's driving me crazy because it's so infrequent I don't get enough chances to troubleshoot and when it does of course it's at an inconvenient time for me to look at what's going on closely.

**Comment by kdschlosser** [comment]
not a biggie. i like the challenge plus i am getting to learn a lot about the inner workings of windows. and the API for it. and also the installation process. PIP and easy_install. at the very least we now have a means to use virtualenv and appveyor without the need for wheels. so that's a really good thing. one less thing to have to maintain. The easiest way for this whole thing to work would be to figure out a way to add EG as a python interpreter to the system and then just launch the installer for pywin32.

**Comment by kdschlosser** [comment]
heyyyy buddy, can you attach a tree with some kind of a macro setup that would cause this issue. I am going to do a normal build and swap out the default tree for the one you provide (that is fi you want to.) then i am going to ask in the forum for people to run it for a while and see if it causes the same issue that you are having. I have tried to replicate the issue on my computer (win7x64) with no success. so i want to get a broader test basis. and make sure it is not something specific to your computer. I hate telling someone that because i do indeed want to know the cause. and I think if no one else has the problem or the problem is isolated to windows 7 i can code around it. every time i get one issue sorted another pops up and sometimes it's something i already worked out but because of a change it causes another issue with what i had just fixed.. and the strange thing is that pywin32 is coded to be in a frozen state (being included with a compiled installer) so it should function as is.. but there are quite a few issues with it already so i do not doubt that it may not work properly. I need to find the best solution. And the unfortunate thing is we really do have to upgrade to this thing because of windows 10. and windows 10 had an enormity of changes it wasn't so bad from windows 7 to windows 8. but windows 10 there are a lot. I don't know if there is a replacement. because it seems like the pywin32 has issues and those issues do not get fixed. and rebain broken.. dde for instance has been broken for 7 years,

**Comment by per1234** [comment]
OK, here they are:

[issue_181_trees.zip](https://github.com/EventGhost/EventGhost/files/751944/issue_181_trees.zip)

The `issue_181_full.egtree` will require installation of https://github.com/per1234/TCPEvents, that's the only non-included plugin it uses. I also added a minimal tree but it's just a **Turn Off Monitor** action. It's possible there is something in the full tree that causes the computer to go into the "susceptible" state but once it's in that state the minimal tree will cause EventGhost to hang.

It's entirely possible the problem is specific to my system. I can of course just use the pre-https://github.com/EventGhost/EventGhost/commit/f62356cf1838cc1c6ab0890e04648416a0d94d47 version of the System plugin and solve the issue for me but I wanted to report the issue in case it could be fixed for everyone.

I may have gotten a clue yesterday. I tried to restart my computer and it couldn't close EventGhost, which was in the locked up state caused by this issue. When I went to manually close EventGhost I saw that it had started working again and 12 hours worth of stuff from the whole time it had been locked up were all zooming through the log. This made me suspect that when Windows killed some process when attempting to restart it un-hung EventGhost. The issue reoccurred today and I tried ending one process at a time in Task Manager to see which one it was but one of them I ended caused the computer to restart automatically before I got through the list. I'll start back where I left off the next time the issue occurs but I'm not sure when that will be.

**Comment by kdschlosser** [comment]
heyyyyyyy I know what it is... i'll bet ya... 

I am going to modify the __init__ of the system plugin and have you test it out for me.

it's sooo friggin stupid too.... but you get no errors from it which is the most annoying thing

**Comment by kdschlosser** [comment]
there are 2 files i am going to send ya. they are both part of the system plugin... try the __init__ first and see if the problem is solved.. and if not then try the other file... 

I believe this issue either has to do with the notifications i added to the PowerBroadcastNotifier.
Or it has to do with the call that is made to change the monitor state..

I believe the issue is that one or the other has to be done from the main thread. which neither of them are. Now i just ran into an issue with random problems caused by receiving notifications when i didn't initialize the thing from the main thread. but it gave me no errors. would randomly stop working... but what i was working with wasn't changing device states. so it would just stop functioning at random times. and then cause all kinds of other issues with EG and receiving notifications form the system.. specifically the power notifications... so I am wondering if it's those that are the cause of the problem.. and when i changed how the plugin turns the monitors on and off it was like poking a bee hive with a stick.. but at any rate i changed it so the plugin will now send the monitor commands from the main thread as well as the power notification now run in the main thread.

so give it a go and see what happens
[System.zip](https://github.com/EventGhost/EventGhost/files/753690/System.zip)

**Comment by per1234** [comment]
OK, I have the __init__,py file installed now and will report my results.

**Comment by kdschlosser** [comment]
Any news? And if it is working would you do me the favor of still trying the other file. You will have to replace the __init__ back to the original. As I believe the better way is in that other file. And I would like to know if it works

**Comment by per1234** [comment]
The issue hasn't happened since I installed your modified `__init__.py` but the power was out here for 1.5 days so it's actually only been tested for 2.5 days. I will test the other file and report my results.

**Comment by kdschlosser** [comment]
what and you don't have a battery backup or a genny???!?! LOL

hell i can tell you where to get a UPS cheap.. and tell you how to modify the thing to probably hold up half your house for about a day if not longer. I really don't know how long mine will last because of how APC does the whole thing with adding battery packs. and not by the battery capacity

**Comment by per1234** [comment]
I haven't had a single occurrence of this issue using the unmodified System plugin since https://github.com/EventGhost/EventGhost/issues/204 was merged so I'm going to close this. Thanks @kdschlosser!

**Comment by kdschlosser** [comment]
no worries m8 I am happy we got it solved... I can't believe how much I have learned about the windows API. it's actually quite overwhelming.

**Comment by per1234** [comment]
Unfortunately this issue has occurred multiple times since I closed it, using up to date versions of EventGhost. It doesn't seem to be happening for anyone else though (or at least nobody has reported it that I've noticed) so may be specific to my system.

**Comment by kdschlosser** [comment]
You can reopen this if you like I believe I found the issue. There is a fix located at this URL http://www.eventghost.net/forum/download/file.php?id=5757

Give this a shot and see if it solves the issue. What I believe was happening is when you would turn a monitor on or off windows would send out a notification. That this has taken place. Now if this error wasn't happening everything would work just dandy. But because it was taking place in the notification thread of windows when the error took place EG could throw a fit and crash not reporting an error but it would also cause the windows notification system to hang and crash. Now this could have many undesirable side effects. So I have fixed that specific problem. Because it is tied to the monitors I thought of this problem and this may be the solution. 

So if you are willing to test it save the file from the URL above to your plugins/system folder overwriting the old one. And let me know if it all goes well

**Comment by kdschlosser** [comment]
@per1234 I may stall. I may slow down. But I do not forget. I will get this problem solved. I got another little tidbit from another bug report that pointed me in the direction of windows notifying eg of various things. And the monitor state is one of those things. And you mentioned a reboot is what unlocked EG so if the notification system in Windows got reset when the reboot process started this would "free" the EG process. Now here is the kicker. Because the notifications take place in the same thread that the GUI runs in this would cause the GUI to hang but not the rest of it.
