### ISSUE TITLE
[System] Start Application disables Command line options if the Executable doesn't end in an executable extension

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#183]
https://github.com/EventGhost/EventGhost/commit/e10f9ebfc6d97196acc450c24017af983870c2ad added code to the System/Start Application action that disables **Command line options**, **Working directory**, **Disable WOW64 filesystem redirection**, and **Run as Administrator** unless the **Executable** field ends in one of the `PATHEXT` extensions. This prevents the use of those options if a variable is used for the **Executable** field. It's also not necessary to specify extensions of executables, why should the user have to hunt down an executable in their path to figure out the extension just so they can use one of the otherwise disabled options?

I see no benefit to this restriction, it only makes the source code more complex and limits the flexibility of the plugin. Why not assume the user is actually smart enough to know what they're doing instead of adding a bunch of harmful "nanny code"?

**Comment by kdschlosser** [comment]
yeah i see what you are talking about.. cpl files should be in that list and aren't

but he added msc files.. which most don't have a clue what those even are. they are for the microsoft management console or MMC 

but i bet ya know what a cpl file is.. LOL

But in all honesty any file that has an association to a program is technically an executable. and when being run from a command prompt the extension would have to be added to PATHEXT

I don't know why the change was made.. there is no information on the commit.. and what "expose undocumented open file/folder behavior" means.. 


also... I want you to check something out for me... because this is odd...

look at the name of the action.. it was changed... but it's not reflected in the add action dialog..

**Comment by kdschlosser** [comment]
I see... there has to be another commit somewhere for this.. because the name is not changed in the release version....

**Comment by topic2k** [comment]
I agree with @per1234 that the user should know what he do. So i would vote for removing the part for enable/disable the options.

**Comment by kdschlosser** [comment]
I agree with you as well on this.  we shouldn't have to babysit.. and EG is complicated enough so that it would require someone using it to have some kind of basic computer knowledge,, and having it set up this way seems a little excessive and restrictive,
