### ISSUE TITLE
Unable to register to forum

### ISSUE THREAD

**Issue by Craigorsarus** [EventGhost/EventGhost#222]
Sorry I know this is the wrong place, but there are no contact details on the website.

I am not getting any activation e-mails for my forum account, I have tried several times over the past couple of weeks - and even disabled every form of spam filtering on my mail server for a while to see if one would come through

Can someone please ask one of the forum admins to look into it? 
(Same forum username as my github account)

**Comment by kdschlosser** [comment]
send an e-mail from the account you used to register to this e-mail address

kevin.g.schlosser gmail 

I think you can figure out my e-mail address. it is to reduce the spam hits. I just need to verify who you say you are..

**Comment by kdschlosser** [comment]
OK here is what i did.. since I am sure this is what has happened.. that username originally registered in 2013 and never activated the account. It was probably you and you have changed your e-mail address since then and don't have that address anymore.. hence the reason why you aren't getting the e-mail. I see no errors related to that username at all.. and since that account has never been used or activated since the 2013 creation date. i just deleted it.. so go ahead and make a new account
