### ISSUE TITLE
Installing the terratec plugin fails on Windows 10

### ISSUE THREAD

**Issue by win10a** [EventGhost/EventGhost#224]
I have installed the latest EventGhost_0.5.0-rc2 on Windows 10 with the latest updates from last week. I want to operate the terratec remote controller, but upon the attempt of automatically downloading and installing the related plugin, after downloading about 4 files, the windows installer comes up with the message "Installation failed", but no more information. Consequentially, the plugin is shown in red and not working.

What could I do to get the terratec plugin to work? Please help!

**Comment by topic2k** [comment]
Run EventGhost from commandline with **`-debug`** parameter, then try again. Watch for the log, there should be more output. Also a log file is generated: **`%APPDATA%\EventGhost\Log.txt`**

**Comment by win10a** [comment]
[eventghost.log.txt](https://github.com/EventGhost/EventGhost/files/966632/eventghost.log.txt)
[Log.txt](https://github.com/EventGhost/EventGhost/files/966633/Log.txt)

**Comment by topic2k** [comment]
Can you please check if this file exists: `C:\ProgramData\eventghost\drivers\winusb\x64\dpinst.exe`

**Comment by win10a** [comment]
dir C:\ProgramData\eventghost\drivers\winusb\x64\
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: xxxx-xxxx

 Verzeichnis von C:\ProgramData\eventghost\drivers\winusb\x64

29.04.2017  14:16    <DIR>          .
29.04.2017  14:16    <DIR>          ..
29.04.2017  14:16         1.047.632 DPInst.exe
30.04.2017  10:06             1.890 driver.inf
29.04.2017  14:16         1.721.576 WdfCoInstaller01009.dll
29.04.2017  14:16         1.002.728 WinUSBCoInstaller2.dll
29.04.2017  14:16         2.152.176 WUDFUpdate_01009.dll
               5 Datei(en),      5.926.002 Bytes
               2 Verzeichnis(se),  3.298.852.864 Bytes frei

**Comment by kdschlosser** [comment]
do you know what the build of windows 10 you are running?

**Comment by win10a** [comment]
Edition               Windows 10 Home
Version               1607
Betriebssystembuild   14393.1066

**Comment by kdschlosser** [comment]
sigh! ya gotta love windows. I am not sure if this is a pre installed version or if you upgraded. but apparently Microsoft was kind enough to lockout the use uf unsigned drivers in 1607. now they stated that it would only do that if it was pre installed. but it appears as tho they didn't pass along the right information. I have had reports of others having issues as well as soon as they upgraded to 1607. Now this might be your issue or it might not be. but I have had others tell me the problem wasn't there before they updated to 1607 and then their drivers wouldn't load either. and as soon as they rolled back the update their device started working again. So I am not sure if you have that ability. or if you have access to another PC with windows 10 with a build prior to 1607 to test on to confirm this is the issue. Unless @topic2k has any other ideas as to what it could be. It will be some time before we go down that road to getting the drivers signed due to Microsoft's requirements. But again it could be some other issue.

**Comment by topic2k** [comment]
One idea: Go to windows device manager and try manually installing the driver for the device. Use the `driver.inf` file from the directory mentioned in previous post.

**Comment by win10a** [comment]
Thank you! Provided with your information I could install the driver with the help of this page:
https://code-bude.net/2015/08/19/windows-10-unsignierte-treiber-installieren/

It basically states, that you can switch off this signitures needing for drivers with startup options of windows.
