### ISSUE TITLE
egplugin import doesn't work if EG is executed as admin

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#229]
If EventGhost is executed and running as administrator and you double click an .egplugin file, a new EG process is created, but you don't see any UI for it. (so for a user nothing happens)
If you now close EG and wait some time, EG comes up again with a warning "Failed to launch for unknown reasons".

EG 0.5 RC 2

**Comment by kdschlosser** [comment]
ok cool. I know what is causing that. it's going to take a bit to figure out a way to fix it.

**Comment by kdschlosser** [comment]
"Failed to launch for unknown reasons". there is a number associated with this error. do you know what it is?

**Comment by ThomasBott** [comment]
Yes, it's -2146959355

**Comment by kdschlosser** [comment]
TY that's the number i wanted

**Comment by kdschlosser** [comment]
here is a link for a build i just did up. I am running windows 7. I want to make sure it work properly on windows 10. If you are interested in testing it out for me, it is the same thing as rc2 except for this change. but here is the link.. I have also attached the file with the fix as well just in case you do not want to run the installer you can simply backup the Cli.py file and put the new one in it's place. It appears as tho whoever added the error checking for the elevated permissions used the wrong error codes. this has been fixed. but I want to test if we can completely do away with any kind of a message box and still get the plugin to install.

Now it may launch another EG window to accomplish this. and if it does let me know. because the plugin list in the first EG would not be refreshed. So I would need to put into place a mechanism to send the path to the plugin file to the EG that has the elevated permissions. But this is a place to start. On windows 7 it currently opens up the plugin install dialog. I just want to cover all the bases with this

here is the link

https://ci.appveyor.com/project/kdschlosser/eventghost-9ivlx/build/366-bugfix-plugin-install-elevated/artifacts

and the Cli.py file is attached. I had to change the extension to .txt so you will need to change it to .py

[Cli.txt](https://github.com/EventGhost/EventGhost/files/1020564/Cli.txt)

**Comment by kdschlosser** [comment]
Any update on this? Has it been tested? If it works I would like to get a PR issued for it

**Comment by topic2k** [comment]
Seems to not work on Win10-64bit. I started EG as administrator and then double clicked as user on xxx.egplugin file. In task manager there come up two more processes, but nothing happens.

**Comment by kdschlosser** [comment]
blah!

this is going to be a tough nut to crack.

**Comment by kdschlosser** [comment]
I have an idea.... if we simply get the elevated permissions error then to restart the instance as elevated. this would cure the problem. i will tinker with it over the next couple of days

**Comment by kdschlosser** [comment]
This is now fixed 

Here is the latest build if you want to give it a test run

https://ci.appveyor.com/api/buildjobs/rd2tnb72ttt8a42s/artifacts/_build%2Foutput%2FEventGhost_WIP-2017.06.23-07.11.07_Setup.exe

**Comment by topic2k** [comment]
fixed via #240
