### ISSUE TITLE
Disable GitHub wiki

### ISSUE THREAD

**Issue by per1234** [EventGhost/EventGhost#236]
Now that the problem causing the eventghost.org wiki to not be editable has been [solved](http://www.eventghost.net/forum/viewtopic.php?t=9701), the GitHub wiki has no purpose and is harmful due to duplicate content. I have merged all the new content from the GitHub wiki to the eventghost.org wiki or the documentation (https://github.com/EventGhost/EventGhost/pull/235).

Please disable the GitHub wiki:
1. Open https://github.com/EventGhost/EventGhost/settings (the **Settings** tab on the EventGhost GitHub repository).
2. Uncheck **Wikis**

**Comment by dequi** [comment]
Well, wait a minute... the MediaWiki is an old version that needs security patches, and the latest version uses a php version that the goDaddy hosting is not offering, so you can't really update. You might want to do it the other way around and disable the MediaWiki.

**Comment by kdschlosser** [comment]
NO SIR!! We got plans. there will be no issues in the very very very near future as far as being able to upgrade what we want and when. WE WILL NOT BE HELD BACK!!!

LOL

**Comment by per1234** [comment]
This has already been discussed on the forum, but I think I should summarize the situation here:

- The current hosting plan is causing problems with forum attachments because it limits the number of files per folder.
- The current host limits our ability to upgrade MediaWiki.

So the hope is that both the above problems will be solved by moving to a new host. The details of that move have not been finalized. The move will require some donations from the community.

The important thing to me is to avoid having duplicate content because it's a huge hassle to keep it synchronized. I do think it's preferable to use a wiki hosted at eventghost.org because the requirement of signing up for a GitHub account to edit the wiki will discourage some contributors. They are more likely to already have an eventghost.org account. I think a GitHub wiki is a reasonable alternative but I tried unsuccessfully to get the non-functional MediaWiki shut down in favor of the GitHub wiki for the last 6 months.

Disabling the GitHub wiki will not cause any of the content to be lost, it will all still be there if the wiki is re-enabled.

I suppose we could just postpone any more work on the wiki project until the hosting situation is resolved. I've been doing a little work on the wiki every day and would like to continue to do so but I don't want to work on something that will just end up getting deleted.

**Comment by kdschlosser** [comment]
Not sure if you want to use the Media Wiki or the GitHub Wiki. Is there an issue with the Media Wiki at the present moment? I am also confused as to why any work has to stop. From my understanding the Media Wiki updates are security patches and nothing that would cause an issue with the work you are doing. I can do more research into this and see if it would create an issue if you like.

**Comment by per1234** [comment]
>Not sure if you want to use the Media Wiki or the GitHub Wiki.

I prefer MediaWiki to GitHub because EG forum users can use their same account for the wiki. I supported the GitHub as an alternative to the broken MediaWiki. If we ended up going with GitHub I think it would be fine, I just want the wiki situation to be resolved. dequi spent a lot of time migrating content to the GitHub wiki, then I spent a lot of time migrating content to MediaWiki. The key is to settle on one and stick with it. When we started working on this wiki project you didn't have any control over the website and the people (person?) who did at that time wouldn't make the effort to actually join in the discussion.

>I am also confused as to why any work has to stop. From my understanding the Media Wiki updates are security patches and nothing that would cause an issue with the work you are doing.

Because dequi suggested that MediaWiki should be disabled and the GitHub wiki used instead, which would make any work I do on the MediaWiki a waste of time. I don't think upgrading to a new version of MediaWiki would have any affect on the wiki content so that should be fine.

**Comment by kdschlosser** [comment]
I would like to have @topic2k provide some input into this. because there is really 3 types of documentation that has to be done. and if we don't set the groundwork for this that everyone is happy with then it will never work properly. we have to have everyone wanting to come together on this. including you @dequi. I know doing work and not using it really really sucks. and I am very sorry for this. 

I want to be able to use everything but we do not want to have duplicate documentation. 

I like the idea of putting the coding/plugin creation documentation on the github wiki. tho i do not like having it in a different place as the rest of it. the reason i like this is because the people that are going to be able to answer the questions are most active on github and also have the knowledge to answer the questions. and to be honest with ya github is an environment suited to code so things like formatting the docs i would imagine would be geared in this direction. where as the Media Wiki is more about getting information on use to a person and would not be geared more so to a specific type of content. and I do not feel there is a need to fatten up the help files in EG with information that the common user would not need/know what to do with so it does need to be split apart in some manner. 

@dequi I am very sorry for all the work you have done and the possibility of it not being used. I personally hate it when that happens. we all do appreciate it very very much. I did not have the access to be able to look into the issued of the media wiki when this work was done. I do have the access now. and I do have the access to change/update things on the website. so getting this plugin repo going is going to be a snap now. I know your work on that stalled due to accessing things on the web server and also not being able to create the backend for it. but going forward this will not happen to ya again. i do apologize for it. and in zain's defense he kept the site and EG doing. he does not have the knowledge to fix things like the media wiki or to advance the code. so better to leave it alone then to make it worse.. he did right in my book. I think he has been waiting for the right group of people to come along and want to help with EG and to get it going in the right place, I think he has found that right group of people. and we need to keep at it. there are going to be some pitbfalls. and trip-ups as what happened here with the media wiki/github wiki and they do hurt like hell when it happens. but as long as we stay focused on the goal and keep on going in that direction everything else will fall into place. The goal with the wiki's and docs is to provide the user with the most convenient and easy to access information they need to successfully implement EG in their home. that being said. I know that github has a HUGE learning curve. and a lot of it is hidden and or is command line only. i do not know if this holds true to the wiki end of it.. and i do not know if the media wiki is any easier. but i really do not consider github to be easy or convenient in any manner. it is really geared to geeks and the majority of the EG users that are out there are not knowledgeable in github and have to busy a life to spend the weeks to learn it. this is the reason why i do like having the scripting/plugin creation portion of the documentation on github. because osomeone that is seasoned is already going to know github. and someone that is new better start learning it because they are going to have to at some point may as well make it sooner then later.

**Comment by dequi** [comment]
> I do think it's preferable to use a wiki hosted at eventghost.org because the requirement of signing up for a GitHub account to edit the wiki will discourage some contributors. They are more likely to already have an eventghost.org account.

> I don't think upgrading to a new version of MediaWiki would have any affect on the wiki content so that should be fine.

I can agree with your reasoning here, and I'll direct my efforts to the mediaWiki accordingly.

> I suppose we could just postpone any more work on the wiki project until the hosting situation is resolved. 

I don't agree, keep going.

> I do have the access now. and I do have the access to change/update things on the website.

Cautiously optimistic about that, it is a start. I had that as well in the past. In my investigation the wiki fix was nothing more then provide the correct user and password to the phpBB database for checking the user is in the wiki usergroup.  Could not implement though.

> I know doing work and not using it really really sucks. and I am very sorry for this.

No need to be sorry, I 'll see my work it as a catalyst that got things moving again, It served it's purpose :smiley:

**Comment by kdschlosser** [comment]
There was something else that i had to change as well. tho i don't remember off the top of my head what it was.

**Comment by topic2k** [comment]
Done :-D
