### ISSUE TITLE
Right to Left bug

### ISSUE THREAD

**Issue by Romank1** [EventGhost/EventGhost#319]
Hi,

I use Windows 10 v1803 x64 English and  EventGhost v0.5.0 rc4.

When I change "Region Format" to Hebrew:
![snap1](https://user-images.githubusercontent.com/4432037/45708695-c3d1fd00-bb8a-11e8-975c-db5746381ea7.jpg)

I get issue with text location:
![snap3](https://user-images.githubusercontent.com/4432037/45708697-c3d1fd00-bb8a-11e8-9681-7c0fa6bbc92c.jpg)

When I change "Region Format" to English, I don't get this issue.
EventGhost 0.4.1 don't have this issue.

**Comment by kdschlosser** [comment]
I need to have a few questions answered.
does Hebrew read right to left or left to right?
do you have the language in Windows set to Hebrew?
what do you have the Location in Windows set to?

I thought that Hebrew is  written and read from right to left. so that by definition should change the orientation of the text to read from right to left having right justification. I am thinking that this would actually be a bug in 0.4.1 and not in 0.5.0.

I am trying to get a better understanding of your setup. There are 3 areas that effect how windows and it's application will display text. the Format tab the Location tab and the Keyboard/Language tab in the Region control panel. I would need to know what all of these are set to in order to be able to give you a solution/answer

**Comment by kdschlosser** [comment]
I didn't want to leave you ganging with this.

Upon investigation... it's half a BUG..
The text being right justified is not.. open internet explorer and see what happens.

Now the whole frame getting reversed.. like the close button ending up on the left.. That is a BUG.. I posted a bug report on the wxPython repository.. I wouldn't hold my breath on getting it fixed any time soon. They seem to not do anything about bugs unless it completely breaks something. If it is how it is getting displayed that is wrong. they will be in no big hurry to fix it. 

The issue with wxPython is that over the years and having so many fingers in the cookie jar so to speak the code is a complete mess. It is not something I am going to try and fix.. I would end up wanting to re wright the whole thing.

I am going to see if there is a way I can turn it off.. If i can do that then I can set an option in EG for it to ignore the those settings in windows.

**Comment by kdschlosser** [comment]
OK good sir. I wanted to make sure I gave you an update. This is indeed a problem in wxPython. specifically the wxWidgets c backend to it. I have been going back and forth with the writer of wxPython. (he is very slow at responding. almost 20 days between replies). I have finally grown tired of it. we also discovered another glitch with the language settings of EG also related to this problem. they both used the same mechanism. which was obviously broken. Now I did tell them how to fix it. along with a very detailed explanation of how the Windows Locale and Languages work. and why they can't do what they were trying to do and that is share code between the different OS's that wxWidgets supports. Their naming conventions are all wrong along along with a bunch of other things.

The reason why this problem occurred is because of the upgrade that we were forced to do when we upgraded the python version to 2.7 wxPython would crash EG unless we set the locale. and we were setting the locale based on that incorrect information obtained from wxPython.

I believe we have fixed the issue at this point. You can test it if you like. If you click on the link directly above this post it will bring you to the pull request for the bugfix. scroll down to the bottom of the page. to the last AppVeyorBot entry. in that box you will see a link to the setup.exe. you can download it there and install it. Be sure to backup everything EG related first. I am not responsibe if something gets alittle wonky on ya. 

copy all files in the locations below to a safe place. be sure to save the data for each location to it's own folder. and name the folder so you know where it goes in the event you need to put everything back the way it was.

    %programfiles(x86)%\eventghost
    %appdata%\eventghost
    %programdata%\eventghost 

you can copy and paste those paths as they are with the %'s right into the address bar of file explorer and press enter. it will bring you to where it needs to go.

**Comment by kdschlosser** [comment]
Has this problem been solved with the new release candidate?

**Comment by Romank1** [comment]
Yes, the problem has been solved with the new release candidate! 

Thanks

**Comment by Romank1** [comment]
The problem has been fixed partially.
The main window is ok, bat other windows have the issue.

![image](https://user-images.githubusercontent.com/4432037/50275463-1223c000-0448-11e9-8807-e30e1a300aac.png)

![image](https://user-images.githubusercontent.com/4432037/50275474-16e87400-0448-11e9-833b-28474252e484.png)

![image](https://user-images.githubusercontent.com/4432037/50275479-19e36480-0448-11e9-93d5-f4ee1ca8b9e6.png)

**Comment by Romank1** [comment]
After some tries, I found that the problem start to appear after i open "Options".

**Comment by thecode** [comment]
I have tracked down the issue to SpinNumCtrl, it will doesn't effect just the options dialog, but any dialog which is  uses the SpinNumCtrl or based on it (such as SpinIntCtrl which is used in option dialog.
The control reloads the locale for the whole app to the system default.
`l = wx.Locale()	THOUSANDS_SEP = eg.app.locale.GetInfo(wx.LOCALE_THOUSANDS_SEP)
l.Init2(language=wx.LANGUAGE_DEFAULT, flags=wx.LOCALE_LOAD_DEFAULT)`

See here:
[https://wxpython.org/Phoenix/docs/html/wx.Locale.html#wx.Locale.Init](url)

> The call of this function has several global side effects which you should understand: first of all, the application locale is changed - note that this will affect many of standard C library functions such as printf() or strftime(). Second, this wx.Locale object becomes the new current global locale for the application and so all subsequent calls to wx.GetTranslation will try to translate the messages using the message catalogs for this locale.

Solution is to use the loaded local from the eg object:
`eg.app.locale`

Added to pull request #356

**Comment by topic2k** [comment]
@Romank1 can you test the wip build from #356 and report if this will fix it for you too? [EventGhost_WIP-2019.01.06-21.49.04_Setup.exe](https://ci.appveyor.com/api/buildjobs/tq4c3vykj4fug4ii/artifacts/_build/output/EventGhost_WIP-2019.01.06-21.49.04_Setup.exe)

**Comment by Romank1** [comment]
Hi @topic2k,

This build fix the problem for me.
Thanks
