### ISSUE TITLE
Eventghost forum inaccessible

### ISSUE THREAD

**Issue by skribb** [EventGhost/EventGhost#343]
when logging in i get error message:
The specified username is currently inactive. If you have problems activating your account, please contact a board administrator. 

 i used the form on http://www.eventghost.net/forum/memberlist.php?mode=contactadmin 
but no reply

and I tried to register a new account with a separate email, and i never received the activation email.

i'm desperately scrambling to find a way to get back into the EG boards so don't be surprised to find more than one msg from me regarding this (i tried to email KG separately as well).

**Comment by kdschlosser** [comment]
ok dude. you should be good to go. check your e-mail address in the profile and make sure you didn't fat finger it. when you change your e-mail address it forces a reactivation email to be sent. I know the email is working because we have new users registering. and I also just sent a test e-mail to my email account from the board and it is working fine. If you are not getting the registration e-mails then the place that hosts your e-mail is not allowing it through. this happens when reverse lookup information on an IP does not match the forward lookup information. Unfortunately we do not own the IPV4 address we have to own one it is very expensive. I have done some things to help ease this issue but some email providers still pitch a fit about it.

**Comment by skribb** [comment]
i have no idea what was wrong, i just use a gmail account but yeah i did change my email a few weeks ago

i can get into the forum now, thanks.
