### ISSUE TITLE
System Event not triggering macro

### ISSUE THREAD

**Issue by coyote-1** [EventGhost/EventGhost#346]
HI,

I am brand new to EventGhost. Looks fantastic.
I created a macro. 

Event: System.SessionUnlock [u'coyote']

Action: <?xml version="1.0" encoding="UTF-8" ?>
<EventGhost Version="1722">
    <Action>
        EventGhost.PythonCommand(u"import urllib; urllib.urlopen('https://confidential http command string:')")
    </Action>
</EventGhost>

When I execute the action item it works fine and has the desired effect on the external system.
The problem is that the System.SessionUnlock event is not triggering the macro.
What am I missing?

**Comment by coyote-1** [comment]
Yes, I did that. 
I should add that it works without the payload.
Is there a way to incorporate the payload, in order to perform external actions based on WHO has unlocked the system?

**Comment by coyote-1** [comment]
Thanks all.... last night I figured it out. I’m concatenation the url to which I’m sending data with the payload as an argument, and performing the logic based on the payload at the receiving site.

That said, the methods you’ve shown here will come in handy for me in future projects. Thanks again, and happy holidays!

**Comment by kdschlosser** [comment]
hey no worries m8. if there is anything else we can do to assist you. Let us know. We have a a group of some pretty knowledgeable people that can almost answer anything computer related.

**Comment by coyote-1** [comment]
Ok, trying to use the method I described to build a string for the speech add-in.
I keep getting the error 
TypeError:_call_() takes at least 6 arguments (2 given)

The string I’m building is identical to that generated by the plugin itself:
eg.plugins.Speech.TextToSpeech(u’Microsoft Sira Desktop - English (United States)’, 0, u’good day’, u’ ‘, 100, u’Speakers (realtek(R) Audio)’)

When I print out my concatenation, it is identical to this.
Yet it generates the TypeError:.

What am I missing with plugins?

**Comment by kdschlosser** [comment]
ok so this is how python works.

This is not a single string. this is a function call that passes information to the Speech plugin.

eg.plugins.Speech.TextToSpeech(u’Microsoft Sira Desktop - English (United States)’, 0, u’good day’, u’ ‘, 100, u’Speakers (realtek(R) Audio)’)

I will break this down into pieces.

the first section which would be everything before the open parenthesis "("

    eg.plugins.Speech.TextToSpeech

This is the function you are calling. Each dot "." represents a nested element.

    eg

being the first element. this represents all of EventGhost. everything related specifically to eventghost will be under this "object." 

the next one is 
    plugins

so we want to access were all of the plugins are located. this is the object that holds them.

I will show you some code you can run and it will help to get a better understanding of what is happening.

    for plugin_name, plugin in eg.plugins.__dict__.items():
        if not plugin_name.startswith('_'):
            print plugin_name + ':', plugin

This will list off all plugins you have installed into your configuration  tree plus all of the core plugins that are loaded. 

so how we are at 

    Speech

this is the name of the plugin we wish to access.

and in that plugin we are looking for the action named

    TextToSpeech

so that is how the first portion breaks down.

the next part which is between the the parenthesis are the parameters (arguments) you want to pass to the action. it is easier if you break i apart and look at it this way

    u’Microsoft Sira Desktop - English (United States)’,
    0,
    u’good day’, 
    u’ ‘,
    100, 
    u’Speakers (realtek(R) Audio)’

the parameters are separated by commas. you have to be careful doing this because the value you are passing can also have a comma in it. so it is easier to remember this.

if you start with a single ' or a double " quote then you will have to have this right before the comma

if you start with a square [ or a curly { bracket then you will have to have a closing bracket ] or } right before the comma.

if you start with an open parenthesis you will have a closing one right before the comma.

when dealing with Python there are 2 types of string. a string that is unicode and one that is not.
unicode strings allow for larger character sets. (for non ascii characters). for instance. If i wanted to store some Chinese text I would do it in a unicode string. How you can tell the difference between the 2 types of strings is that you will see a "u" before the first quote. if you do not have any non ascii characters in your string you do not have to have the u in the front. if you are simply passing data from one thing to another you cannot just add the u. the string would need to be encoded. which will make that u appear when you print the text. The u is not really there. it is simply a way for us to be able to easily hard code text and have it stored as unicode.


This is the parameter set that the action needs to have passed to it.

    voice, rate, voiceText, suffix, volume, audio

and if we align those with the values from above.

parameter name|data being passed
-------------------|-----------------------
voice|u’Microsoft Sira Desktop - English (United States)’
rate|0
voiceText| u’good day’
suffix|u’ ‘
volume|100
audio|u’Speakers (realtek(R) Audio)’

The only parameter you probably want to change is the voiceText. this is what is actually being spoken

The rest of the parameters are as follows

voice = the Micosoft TTS Voice
rate = The speed to speak the text
voiceText = what you want to have spoken
suffix = the suffix of the event that gets generated when the playback starts and stops
volume = I think you know what this is
audio = the sound device on your computer you want to have the playback heard on. 


as a simple example script you can paste into a python script and run

    import time
    for i, text in enumerate(['Testing', 'One', 'Two', 'Three']):

        eg.plugins.Speech.TextToSpeech(
            ’Microsoft Sira Desktop - English (United States)’,
            0,
            text, 
            'TEXT' + str(i), 
            100, 
            ’Speakers (realtek(R) Audio)’
        )
        time.sleep(2.0)

**Comment by coyote-1** [comment]
Thanks for that lesson. I know about the arguments, but this helps clarify it.
Indeed I was only seeking to change the text string - and I was trying to do two things with it:
1. Insert the name of the user who has just reactivated a session on to the machine
2. Make an announcement based on time of day.
So if I log on at 9am, it would say “good morning, coyote” - if I log on at 3pm, it would say “good afternoon, coyote”.

I managed to insert the username by putting payload[0] directly into it as part of the text argument, rather than putting it in another variable. When I get home from work this evening I’ll look at this more closely.

The other thing I’ll want to do with this is have it occur when my wife reactivates a session. Right now, it only announces when I get on the machine (though the script does indeed know she has logged on - it successfully passes the “who logged on” variable to another system).

**Comment by kdschlosser** [comment]
so let me get a better understanding of your layout.. I think for me to be able to suggest the best setup I am going o need to know this.

Now tell me if I am right or wrong. But from what I am guessing is that your setup is more like a client server scenario

where you have more then a single machine and only one of them makes the announcement?


the time of day is pretty easy to handle.

```python
import time

# gets the number of seconds that has passed since epoch until now
# epoch = Jan 01, 1970 00:00:00 UTC
now = time.time()

# since "now" is for the UTC timezone. we need to
# convert it to your local time zone.
local_time = time.localtime(now)

# There are many ways to accomplish this next bit. But i have found this
# to be the easiest. you can convert the time into any kind of a string
# format you want. there is a complete list of format options located here
# http://strftime.org/
# as en example if you supply %H:%M:%S as the string format the returned 
# value will be the current time in 24 hour representation Hours:Minutes:Seconds
# we are only interested in what hour of the day it is. so the %H will give us 
# the hour of the day on a 24 hour clock. 
# we then want to convert that into an integer to make it easier to do some 
# simple comparison operations on. 

hour = int(time.strftime('%H', local_time))

# less then 12pm
if hour < 12:
    print 'Good morning'
# between 12pm and 5pm 
elif hour < 17:
    print 'Good afternoon'
# after 5pm
else:
    print 'Good evening'
```

we can now compress that code into the following

```python
import time

hour = int(time.strftime('%H', time.localtime( time.time())))
if hour < 12:
    print 'Good morning'
elif hour < 17:
    print 'Good afternoon'
else:
    print 'Good evening'
```

we can also create a lookup table to create a more formal announcement

```python
USERS = {
    'coyote': 'YOUR FORMAL NAME HERE',
    'WIFE_USERNAME_HERE': 'WIFE NAME HERE',
}
```

**Comment by kdschlosser** [comment]
I am not sure what you mean by security system.. is it a PC or some kind of software?  I have never seen a dedicated security system that is able to integrate with Tasker. 

Is it a single computer we are dealing with that you wish to get the session information from?.  because we can get it from all Windows computers you have on your network. and it can be done with a single running copy of EG.

Now the reason why you are not getting the session information when your wife logs in is because you do not have a copy of EG set up to start when she signs on.

EG is very much user specific. it is an application. not a service. so when you logoff it shuts down EG. You can try using UAC and fast user switching to change to a different user this should keep EG running.

This gets a wee bit complicated because of how Windows handles multiple users being logged in at the same time. Because EG is an application and not a service if you have more then one user signed on and in each of those running sessions you have EG running, you can end up bumping heads if you are not careful. an example would be having both sessions having an identical macro and trying to access the same resources at the same time. this will create a whole plethora of problems. 

You can do the above but you have to do it with care. If you do not use fast user switching (having more then one user logged in at the same time). You can do the above without issue. and you would place the saved tree into a location that is not in the profile space of any user so any user can access it without permissions issues. and you would setup EG to start for any user you want this to work for and have EG automatically load the tree that you have in a common location.

**Comment by coyote-1** [comment]
I wrote a simple vb script to have the computer say “good ________ (morning, afternoon, evening) wife” and am triggering it from Windows event scheduler. Of course you know this already, but all the events in EG can be accessed from there.

**Comment by kdschlosser** [comment]
again it is still an issue with the UAC. any time you are dealing with more then a single user it gets a bit hairy working with EG unless you have EG running on a dedicated machine (or user account) the risk of ending up with more then one instance of EG running at the same time and bumping heads can cause your system to become unstable. so you have to be careful not to use Fast User Switching.

The end game is that you need to set up EG to run for each user that logs in. EG can handle all of the tasks you require. It is going to be far simpler to maintain if you can keep everything in a single place. instead of piecing things together. If you also want to track user logons to the computer I do not know who your cell phone provider is by you may be able to use the Text Message plugin to have EG send your phone a text message when a user logs in or out.

> Of course you know this already, but all the events in EG can be accessed from there.

I am not sure exactly what you mean by this. You will need to give me a little more detail

**Comment by coyote-1** [comment]
Windows has an event scheduler/manager. Has had it since WinNT. It’s now called Task Scheduler.
You can use it not only for scheduling things (like backups), but you can use system events to trigger actions. And because it’s working at a system level, it is not limited to just one user.

And I’m more comfortable with VB scripts, so that’s what I used for this simple task.

**Comment by kdschlosser** [comment]
if that works for you then great. I know about the task scheduler. it is the place where malware and spyware like to install things into. You also have google that uses it to check to see if their update service for chrome has been removed or disabled. and it will reinstall/enable it if it has been.
