### ISSUE TITLE
Finish the new "Add Event..." dialog

### ISSUE THREAD

**Issue by topic2k** [EventGhost/EventGhost#40]
It's already broken since at least version 0.4.1.1509 (the oldest i have/could run).

Clicking on a node to expand it, raises an exception:

```
Traceback (most recent call last) (0):
  File "D:\devel\EG-plum\eg\Classes\AddEventDialog.py", line 188, in OnExpanded
    self.tree.GetPyData(event.GetItem()).expanded = True
  File "D:\devel\EG-plum\eg\Classes\PluginModuleInfo.py", line 89, in __setattr__
    "%s has no attribute %s" % (self.__class__.__name__, name)
AttributeError: PluginInstanceInfo has no attribute expanded
```

Clicking "Ok" although raises an exception:

```
Traceback (most recent call last) (0):
  File "D:/devel/EG-plum/EventGhost.pyw", line 54, in <module>
    eg.Main()
  File "D:\devel\EG-plum\eg\__init__.py", line 83, in Main
    stackless.run()
  File "D:\devel\EG-plum\eg\Classes\MainFrame\__init__.py", line 1174, in OnCmdAddEventDialog
    label=label
  File "D:\devel\EG-plum\eg\Utils.py", line 161, in AssertWrapper
    return func(*args, **kwargs)
  File "D:\devel\EG-plum\eg\Classes\UndoHandler\NewEvent.py", line 53, in Do
    result = eg.actionThread.Func(ProcessInActionThread)()
  File "D:\devel\EG-plum\eg\Classes\ThreadWorker.py", line 64, in __call__
    self.returnValue = self.func(*self.args, **self.kwargs)
  File "D:\devel\EG-plum\eg\Classes\UndoHandler\NewEvent.py", line 34, in ProcessInActionThread
    for child in parent.childs:
AttributeError: 'NoneType' object has no attribute 'childs'
```

What should this dialog do? Simulate an event?
Is it ok to remove this function?

**Comment by blackwind** [comment]
I wasn't even aware we had a debug menu. Gonna need a little more information on how to trigger this one before I can make a call one way or the other.

**Comment by topic2k** [comment]
Just call EG from command line with -debug as paramater.

**Comment by blackwind** [comment]
Boy, this thing is a mess. It was originally hanging for me on startup until I renamed my config file, ran the program again, and renamed it back. I do see the original error now when I open that dialog, but when I press OK, it hangs again. Everything I touch in the menu either triggers a traceback or a hang. Is there any point to any of this at all?

**Comment by blackwind** [comment]
Alright, I see now why you made those extra changes to the `Webserver` plugin. I've gone ahead and committed a slightly better solution, and now debug mode works for me without hanging.

What `AddEventDialog` appears to be is a way to showcase all static events each plugin can trigger so you don't have to go Googling or ask on the forum if there's a way to do \<x\>. To make it workable, the following would need to happen:

* The errors you pointed out need to be addressed.
* A text entry control needs to be added to the bottom-left corner.
* When an item is selected from the list, the corresponding event should appear in the textbox.
* When OK is pressed, the event that's added is whatever is currently in the textbox. This way, the user can enter something like `Keyboard.Shift+Ctrl+P` himself, which wouldn't be in the list because it's not a static event.
* Static events would need to be declared in each plugin the way the `System` plugin apparently already does. Any plugin that doesn't explicitly declare events (like `Mouse`, `Keyboard`, and `Task` currently) shouldn't be included in the list, as there's no sense in displaying empty items.

When the above criteria are met, the current "Add Event..." dialog can then be replaced with `AddEventDialog`.
