### ISSUE TITLE
Forum down

### ISSUE THREAD

**Issue by ThomasBott** [EventGhost/EventGhost#416]
I can't reach the EventGhost website/forum since some days - did someone forget to pay the bill for electricity or something? ^^

**Comment by ekutner** [comment]
Is the project even alive? The last commit was a year and a half ago.

**Comment by ThomasBott** [comment]
Well, I hope so, I'm developing plugins for it :D

**Comment by kdschlosser** [comment]
The site is up and running. Life events have greatly changed and limited the amount of time I am spending working on EventGhost. I am working on it I have not pushed any changes to the repository as the changes are a complete ground up rewrite of the code. I am not finished with the rewrite but expect to see EG running as a service/daemon, cross platform support, web based management, cross platform client application that will forward GUI related and User related information to a "server" instance of EG. The client app will handle actions and events that are only accessible once a user has logged into a computer. Some examples are clipboard and interaction with application windows.

There is a large amount of learning in order to make it cross platform and not have multiple code bases to support. To have the application be able to be run as a service/daemon was pretty difficult to do in and of it's self. The new code base is still going to be written in Python (3.9) but it is not going to run as python code. The code is compiled into a C extension which allows it to run some 200 times faster and any sensitive information (usernames, passwords and encryption keys) will be encrypted and split then compiled across several files making it a daunting task for a would be hacker to obtain the information easily. Communications between the client application and the service are done by using either a loopback network interface or a public/private network interface and all communications between the client and service is going to be encrypted. This encryption process is one of the reasons for having EG compiled into a C extension as the encryption process is simply too much for Python to do in an efficient manner.

**Comment by ThomasBott** [comment]
Hi Kevin, thanks for fixing the page and great to see you're still around! I can confirm it's working again.

Sounds like a huge undertaking! Having work and family myself, I know how hard it is to find time for Hobbys/development. It sounds great though! But a friendly advise; try to split the improvements in as many packages/releases as possible.. going for a "big bang" is rarely gonna work

**Comment by kdschlosser** [comment]
Trust me I have thought about that a lot.  Because  of how EG is written there is no way around it. It is impossible to do incremental changes because how how woven into the code wxPython is and also all of the Windows specific API calls.  It is by far easier to start over then it is to modify EG by writing patchwork code which ultimately ends up being buggy. If moving EG to a service wxPython MUST be removed. and in order to remove it it has to be replaced with another type of GUI. Also any code that is written into the core of EG that interacts wit the desktop or user accounts must also be removed. 

If EG was originally written in a more modular manner it could be done in multiple releases/packages but unfortunately that is not the case. I have stared at the code for many years now thinking of ways to make it easier and I have not come up with any solutions that won't be problematic.

**Comment by ekutner** [comment]
Happy to learn it is still being actively developed. Thank you for the great work!

**Comment by ThomasBott** [comment]
> Trust me I have thought about that a lot...

That's not how I meant it.. I wasn't refering

**Comment by kdschlosser** [comment]
Is the server down again?

**Comment by Saxtus** [comment]
> Is the server down again?

It works fine from here.
You may want to check first before doing a claim like this.
Example website for checks: [https://check-host.net/check-http?host=eventghost.net](https://check-host.net/check-http?host=eventghost.net)

**Comment by kdschlosser** [comment]
It was down before. I just wasn't sue if it had gone down again because the topic got reopened

**Comment by ThomasBott** [comment]
My bad, hit the wrong button.. thick fingers ;)

**Comment by kdschlosser** [comment]
OK cool. just had me worried there because it was up where I am sitting from didn't know if something else was going on.
This time is the only down time the server had had in 2 years time. Not sure why i had to reboot it but I did. Nothing showed up in the logs at all. it was strange.
