### ISSUE TITLE
Setup has no option for custom setup

### ISSUE THREAD

**Issue by topic2k** [EventGhost/EventGhost#76]
When running the setup for 0.5.0 beta 1 there is no option to choose the directory to install into. It just installs into the directory of the previous installed version.

**Comment by blackwind** [comment]
This is an Inno Setup design change and not anything I did. If I roll back to v5.4.3, it'll offer the dialog again, but there's a reason I can't recall right now why I'm using v5.5.9.

I assume the reason they do this is because there'll be no obvious way to uninstall the previous copy if you install somewhere else, as the start menu uninstall shortcut and the uninstall entry in Programs & Features will point to the new copy.

Personally, I like it this way. Makes things easier for the user. If you really need to run two installations side by side, you can always rename the old folder before updating like I did.
